# Generated by Django 4.2.17 on 2024-12-17 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0004_question_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('current_working', models.BooleanField(default=False, verbose_name='Currently Working')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship')], default='Job', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('qualification', models.CharField(default='Not Specified', max_length=255)),
                ('role_responsibility', models.TextField(default='Not Specified')),
                ('skills', models.CharField(default='Not Specified', max_length=255)),
                ('description', models.TextField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('post_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('prn_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
